= Novo Selo, Ritual e Adendo (Pequenos Insights)

== Novo Sêlo deste

卍 (♃·I.M.·⛧) 卐

=== Adendo: Pequenos Insights

==== Perfeição

Dizer que a Perfeição é inatingível é análogo a reconhecer que não há possibilidade de fidelidade conjugal, isto é, de uma inviolabilidade.

==== Dignidade

O homem aparentemente precisa de pouco para manter sua dignidade. Cogito se ainda é possível “tendo muito.”

==== Amor-Compaixão

Eu tenho a impressão, pelos meus escrúpulos sociais, que o homem chega à um ponto em que ele deveria abrir o seu coração e incendiar-se em amor, enfrentando o que tiver para ser enfrentado, permitindo o **tudo**.

==== Pequena Técnica para Escrita

Escreva, escreva como se fala, discursa, por ex. “tevê.” Escreva com design em mente.

==== Vitória

Existe vitória dentro do finito; é fora dele que não existe. Admito que escrevo com interesses pessoais, no entanto creio no que escrevo, tendo em vista a imobilidade que o medo põe sobre os homens.

==== Mães

Quando tu te perguntas...

Qual a postura que um homem deve tomar diante de uma mulher só e com uma criança de colo?

Uma só [é a postura,] sim é sim, não é não, etc.

==== Amigos

Publicar um ensaio de como as amizades humanas são movidas por auto-interesse e portanto uma tolice buscar por eles...

E o oposto disso, sendo auto-suficiência, ser completo.

==== Tesão

O tesão com papo rola com praticamente 100% das mulheres bonitas. (não importa suas idéias ou elevação moral.)

==== O Escravo X O Homem Livre

A consciência dos escravos nõ compreende a consciência dos homens livres; portanto, tu não precisas te preocupar com o teu flerte, o I.M., com as mulheres bonitas que sentam perto de ti na lancheria, como parecerá aos olhos alheios. (21/02/2017)

==== O Eixo

NÃO HÁ VERDADE FORA DO CENTRO! Que eu sempre me lembre do centro.

==== Um Espelho

(Sobre as pessoas ficarem me fitando procurando o que há, Aquilo que Há em mim,)

Eu escrevi diversas vezes sobre o **espelho**, no entanto, na questão das mulheres e sua paixão, será mesmo um assunto de *espelho*?

==== Apenas Permitir

Eu sinto que eu devo ir atrás de mulheres livres. Se uma mulher se interessar por mim, não sendo livre, e eu por ela, ótimo, mas acho que devo respeitar seus limites caso contrário.

Que parta dela! Quanto às mulheres lives? Se houver interesse, então sorrisos e carinho e atenção e conversa!

== Fim do Post

"]