= O Gênio Perfeito

O ponto sólido que o homem possui (para entender o funcionamento de si e do mundo) é o **gênio**. Que o ser humano contemple o gênio humano, o homem extraordinário.

O homem extraordinário é sustentado por uma força; aparentemente essa força é o **amor** ou o entusiasmo.

Não pense em custo; pense na vibração energética do teu universo. Quer loucura, então não vibre uma mentira como vida sólida, solidez de realidade. Desenvolva tua mente não apenas na meditação, mas também na **expressão do bem amado**.

Assim, vibra teu universo na vibração da tua música e da tua disciplina.

Algo que nunca me atacou, foi a brisa da excentricidade; sempre que fui excêntrico, sempre que me permiti **ser**, tudo sempre correu bem. (Anahatta)

Observa bem o **Círculo** na vibração do teu universo.

Soletra b-r-i-s-a; era tudo feito de bolha e vento.

O contraste dos muitos sentimentos-devaneios dá aos homens a impressão de que a existência é real, concreta, sólida. Como, se essa impressão é baseada em objetos impermanentes e parciais?